name: Artifacts example exercise

on:
  push:

env: 
  ARTIFACT_NAME: example-name-artifact

jobs:
  uploads:
     runs-on: ubuntu-latest
     steps:
         - name: Checkout Code
           uses: actions/checkout@v4

         - name: Upload Artifact 
           uses: actions/upload-artifact@v4
           with:
               name: ${{ env.ARTIFACT_NAME }}
               path: README.md
      
  
